---
title: "SAE modéle linéaire"
output: word_document
date: "2025-02-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dataset = read.csv2("simplifiedAmesHousing.csv",stringsAsFactors = TRUE, header = TRUE,sep=";",dec=".")
str(dataset)
summary(dataset)
```

## Import des library
```{r}
library(ggplot2)
library(dplyr)
library(car)
```

## Quelques visualisations et interprétations
```{r}
hist(dataset$Lot.Area, 
     main = "Répartition des tailles de maisons",
     xlab = "Surface du terrain (Lot.Area)",
     ylab = "Fréquence",
     col = "skyblue",
     border = "white")#  La repartition de la taille des maisons reste homogéne mais il y'a quelques valeur 
```

```{r}
boxplot(dataset$Lot.Area)
# on note quelques valeurs abberantes 
```
## Corriger les types de variables
```{r}
dataset$Overall.Qual<-as.factor(dataset$Overall.Qual)# typer la variable qualité en factor
```

## Traiter les données manquantes
```{r}
# Compter les valeurs manquantes dans chaque colonne
colSums(is.na(dataset))
```


```{r}
# modifier les levels d'abord
dataset$Alley<-factor(dataset$Alley,levels = c("Grvl", "Pave", "None"))

dataset$Total.Bsmt.SF<-as.numeric(dataset$Total.Bsmt.SF)
# Remplacer NA  de la colonne Alley par None car n'etant pas des Not a Nomber d'aprés le description
dataset$Alley[is.na(dataset$Alley)] <- "None"
summary(dataset$Alley)

```
## Utiliser la régression pour imputer les valeurs manquantes
```{r}

# Liste des colonnes contenant des NA
cols_avec_na <- names(dataset)[colSums(is.na(dataset)) > 0]
print(cols_avec_na)
# indice des individus 
for (col in cols_avec_na) { # uen boucle qui permet de d'indiquer les indices des NA
  indice <- which(is.na(dataset[[col]]))  
  print(indice)
}
# on remarque les NA proviennent de 3 individus d'indice 1342,1498 et 2237

#dataset[1342,]


dataset_sans_na =na.omit(dataset)# 
colSums(is.na(dataset_sans_na))

```
## boxplot de la cible en fonction de 

```{r}
boxplot(dataset$SalePrice~dataset$MS.Zoning,notch=TRUE)
```


